In [1]:
import tensorflow as tf

## Low level API for TF2
---
Very similar to `torch` - essentially create arrays that behave similar to numpy arrays (called _tensors_), but have the benefit of GPU/TPU support, and most importantly have autograd functionality.

Main modules for the low level API:

 - `tf.math`
 - `tf.linalg`
 - `tf.signal`
 - `tf.random`
 - `tf.bitwise`

### Creating tensors and basic operations

In [39]:
# create a basic tensor using tf.constant. Same syntax as numpy
# note that tf.constant are immutable -> cannot use them as weights in a network
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(t)

# tensors have .shape, .dtype attributes
print(f"Shape of tensor: {t.shape}")
print(f"Dtype of tensor: {t.dtype}")

# can get the underlying data back as numpy array with
print(f"Data as numpy array is:\n{t.numpy()}")

# indexing works like numpy
print(t[:,1:])

# many of the usual operators are overloaded to work on tensors also
# eg plus just calls the function tf.add, similar for square
print(t + 5)
print(tf.add(t, 5))

print(t ** 2)
print(tf.square(t))

# matrix multiplication
print(t @ tf.transpose(t))
print(tf.matmul(t, tf.transpose(t)))

# some differences
###################

# in TF, np.mean -> tf.reduce_mean, np.sum -> tf.reduce_sum, np.max -> tf.reduce_max, np.log -> tf.math.log

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Shape of tensor: (2, 3)
Dtype of tensor: <dtype: 'float32'>
Data as numpy array is:
[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 6.  7.  8.]
 [ 9. 10. 11.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 6.  7.  8.]
 [ 9. 10. 11.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


### TF variables
These are just mutable versions of tensors above, so can be used for weights and other things that may need to change.

In [48]:
# can create variables from tensors, or with constructor syntax like numpy
v = tf.Variable(t)
print(v)

# now we can assign to it
v.assign(2*v)
# note assign operator is inplace!
print(v)




<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
